import Head from "next/head";
import Menu from "../components/menu/Menu";
import Hero from "../components/hero/Hero.js";
import Ads from "../components/ads/Ads.js";
import Realizacje from "../components/realizacje/Realizacje";
import Faq from "../components/faq/Faq";
import Testemonials from "../components/testemonials/Testemonials";
import WhyUs from "../components/whyus/WhyUs";
import Contact from "../components/contact/Contact";
import Footer from "../components/footer/Footer";

export default function Home() {
    return (
        <div>
            <Head>
                <title>
                    OhhSite. Tworzymy strony internetowe
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,600;0,800;1,100;1,300;1,400;1,600;1,800&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <Menu />
            <Hero />
            <Ads />
            <div
                style={{
                    width: "100vw",
                    backgroundColor: "#0F0F0F",
                    marginTop: "10px",
                }}
            >
                <Realizacje />
                <Faq />
            </div>
            <Testemonials />
            <WhyUs />
            <Contact />
            <Footer />
        </div>
    );
}
