import Head from "next/head";
import Menu from "../components/menu/Menu";
import ContactForm from "../components/utils/ContactForm";
import Footer from "../components/footer/Footer";
import { useEffect, useState } from "react";
import axios from "../axios";
import styled from "styled-components";
import Iframe from "react-iframe";

const KontaktContainer = styled.div`
    display: flex;
    margin: 0 auto;
    width: 80vw;
    height: 75vh;
    align-items: center;
    position: relative;
    @media (max-width: 992px) {
        flex-direction: column-reverse;
        height: auto;
        width: auto;
    }
`;
const MapContainer = styled.div`
    width: 600px;
    height: 450px;
    @media (max-width: 992px) {
        width: 95vw;
        margin-top: 10%;
    }
`;

export default function Kontakt() {
    return (
        <div>
            <Head>
                <title>test</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,600;0,800;1,100;1,300;1,400;1,600;1,800&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <Menu />
            <KontaktContainer>
                <MapContainer>
                    <iframe
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d9570.887356818474!2d23.08159944664629!3d53.15108649736534!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471ffc93377c3dab%3A0x8e15da48e0220fa1!2sBacieczki%2C%20Bia%C5%82ystok!5e0!3m2!1spl!2spl!4v1624113116904!5m2!1spl!2spl"
                        style={{
                            border: 0,
                            width: "100%",
                            height: "100%",
                        }}
                        allowfullscreen=""
                        loading="lazy"
                    ></iframe>
                </MapContainer>
                <ContactForm />
            </KontaktContainer>

            <Footer />
        </div>
    );
}
